///$tab Main
SET ThousandSep='.';
SET DecimalSep=',';
SET MoneyThousandSep='.';
SET MoneyDecimalSep=',';
SET MoneyFormat='$ #.##0;-$ #.##0';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='D/MM/YYYY';
SET TimestampFormat='D/MM/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='es-CO';
SET CreateSearchIndexOnReload=1;
SET MonthNames='ene.;feb.;mar.;abr.;may.;jun.;jul.;ago.;sep.;oct.;nov.;dic.';
SET LongMonthNames='enero;febrero;marzo;abril;mayo;junio;julio;agosto;septiembre;octubre;noviembre;diciembre';
SET DayNames='lun.;mar.;mié.;jue.;vie.;sáb.;dom.';
SET LongDayNames='lunes;martes;miércoles;jueves;viernes;sábado;domingo';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';


LET vRutaQVDExtraccionXlsx = '\\epm-file02\aplic\Service_Desk\Remedy_epm\Auditoria\Evaluación vigente\';//cargar
LET vRutaQVDExtraccion = '\\epm-file02\aplic\DGYD\DerechosAutor\QVD\Extracted\'; //guardar


///$tab CONEXION JDE
LIB CONNECT TO 'CONEXION_ONEWORLD (epm_dcarmond)';

///$tab 1.1. Activos_OneWorld
// Todos los activos
Activos_OneWorld: 
select
to_char(rtrim(ltrim(FAASID))) as "[FAASID] - Serial Number",
FADSP as "[FADSP] - Date Retired",
PDDTAEPM.JULIANOAGREG(FADSP) as "[FADSP] - Date Disposed or Retired",
FANUMB as "[FANUMB] - Asset Number",
FAAAID as "[FAAAID] - Parent Number",
FAAFE as "[FAAFE] - AFE Number",
FAADDS as "[FAADDS] - State",
FAAOBJ as "[FAAOBJ] - Asset Cost Account - Object",
FADL01 as "[FADL01] - Description",
FADL02 as "[FADL02] - Description 02",
FADL03 as "[FADL03] - Description 03",
FADSCC as "[FADSCC] - Compressed Description",
FACO as "[FACO] - Company",
FAAPID as "[FAAPID] - Unit Number",
FASEQ as "[FASEQ] - Sequence Number",
FAACL1 as "[FAACL1] - Major Accounting Class",
FAACL2 as "[FAACL2] - Major Equipment Class",
FAACL3 as "[FAACL3] - Manufacturer",
FAACL4 as "[FAACL4] - Model Year",
FAACL5 as "[FAACL5] - Usage Miles or Hours",
FADSUB as "[FADSUB] - Accum Depr Acct - Subsidiary",
FAXMCU as "[FAXMCU] - Depreciation Exp - BU",
FAXOBJ as "[FAXOBJ] - Depreciation Exp - Object",
FAXSUB as "[FAXSUB] - Depreciation Exp - Subsidiary",
FAJCD as "[FAJCD] - Contract Date",
PDDTAEPM.JULIANOAGREG(FADEXJ) as "[FADEXJ] - Date Expired",
FAINSP as "[FAINSP] - Policy Number",
FAINSC as "[FAINSC] - Insurance Company",
FAINSM as "[FAINSM] - Renewal Month",
FAINSA as "[FAINSA] - Insurance Premium",
FAAIV as "[FAAIV] - Insurance Value",
FAINSI as "[FAINSI] - Value Index (future)",
FAUSER as "[FAUSER] - User ID",
PDDTAEPM.JULIANOAGREG(FALCT) as "[FALCT] - Date Last Changed",
FAMCU as "[FAMCU] - Business Unit",
FALOC as "[FALOC] - Location",
PDDTAEPM.JULIANOAGREG(FADAJ) as "[FADAJ] - Date Acquired",
FAEQST as "[FAEQST] - Equipment Status",
FANORU as "[FANORU] - New or Used on Acquisition",
FAAESV as "[FAAESV] - Estimated Salvage Value",
FAARPC as "[FAARPC] - Replacement Cost",
FAWOYN as "[FAWOYN] - Allow Work Order",
FACRTL as "[FACRTL] - Criticality",
FAWRFL as "[FAWRFL] - Warranty Flag",
FAWARJ as "[FAWARJ] - Warranty Expiration"

FROM PDDTAEPM.F1201;
/*--where
--FAAOBJ = '167002'
--AND (FADL01 like '%COMPUTADOR%' or FADL01 like '%WORKSTATION%')
--AND FADSP = 0*/

Store Activos_OneWorld into [$(vRutaQVDExtraccion)Activos_OneWorld.qvd](qvd);
Drop Table Activos_OneWorld;

///$tab 1.2. informe_computer_system_all
informe_computer_system_all:
LOAD
    Instancia,
    "Fecha de último examen",
    "Ultima Modificacion",
    "Numero Serial",
    "Nombre CI",
    "Numero Activo",
    "Rol del sistema",
    "Estado Manual (Estado)",
    "Motivo Estado Manual",
    "Estado CM",
    "Motivo del Estado CM",
    "Categoria (Nivel 1)" as Categoria_Nivel_1,
    "Tipo (Nivel 2)" as Tipo_Nivel_2,
    "Item (Nivel 3)" as Item_Nivel_3,
    "Modelo (Nombre de producto+)" as Modelo_Nombre_producto,
    Fabricante,
    Contrato,
    "Empresa Suministradora",
    "Fecha Compra (Fecha adquisicion)",
    "Fecha Inicio Garantia",
    "Fecha Fin Garantia",
    "Fecha Inventario",
    "Fecha Repotenciacion",
    "Contacto Primario",
    "Contacto Propietario",
    Cedula,
    LOGIN,
    Correo,
    "Centro de Costos",
    "Nombre Centro de Costos",
    "Departamento CI",
    Organizacion,
    Empresa_Propietaria,
    Filial,
    "Region (Zona)",
    "Site Group (Grupo Ubicaciones)",
    "Site o Edificio (Ubicación)",
    Piso,
    "Empresa Sede"
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/informe_computer_system_all.xlsx]
//(ooxml, embedded labels, table is [informe_computer_system_all - 1]);

FROM [$(vRutaQVDExtraccionXlsx)informe_computer_system_all.xlsx]
(ooxml, embedded labels, table is [informe_computer_system_all]);

Store informe_computer_system_all into [$(vRutaQVDExtraccion)informe_computer_system_all.qvd](qvd);
Drop Table informe_computer_system_all;
///$tab 1.3. InventarioServidoresWindows
InventarioServidoresWindows:
LOAD
    Servidor,
    Dominio,
    //"Agente SCCM",
    "Agente MCM",
    OS
   
// FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/InventarioServidoresWindows.xlsx]
// (ooxml, embedded labels, table is [Reporte Inventario Servidores]);

FROM [$(vRutaQVDExtraccionXlsx)InventarioServidoresWindows.xlsx]
(ooxml, embedded labels, table is [Reporte Inventario Servidores]);


Store InventarioServidoresWindows into [$(vRutaQVDExtraccion)InventarioServidoresWindows.qvd](qvd);
Drop Table InventarioServidoresWindows;
///$tab 1.4. InventarioServidoresNoWindows
InventarioServidoresNoWindows:
LOAD
    NOMBRE,
    DESCRIPCION,
    ROL,
    AMBIENTE,
    TIPO,
    "SISTEMA OPERATIVO"
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/InventarioServidoresNoWindows.xlsx]
//(ooxml, embedded labels, table is Hoja1);

FROM [$(vRutaQVDExtraccionXlsx)InventarioServidoresNoWindows.xlsx]
(ooxml, embedded labels, table is [Hoja1]);

Store InventarioServidoresNoWindows into [$(vRutaQVDExtraccion)InventarioServidoresNoWindows.qvd](qvd);
Drop Table InventarioServidoresNoWindows;
///$tab 2.1.CMDB_ContratosVsLicencias
CMDB_ContratosVsLicencias:
LOAD
    "Id del contrato de software",
    Nombre,
    Estado,
    Fabricante,
    "Centro Actividad / Centro de Costos",
    "Suministrador Responsable",
    "Empresa Propietaria",
    "Fecha de Creacion",
    "Fecha de Caducidad",
    "Fecha Modificada",
    "Nombre del producto" as Nombre_Producto,
    "Nombre Proveedor", 
    "Orden de Compra",
    Clave__c,
    "Suma Número de Licencias Adquiridas",
    Filial,
    "Información Adicional / Descripción"


FROM [$(vRutaQVDExtraccionXlsx)CMDB_ContratosVsLicencias.xlsx]
(ooxml, embedded labels, table is [Contratos vrs Licencias Nuevo]);

Store CMDB_ContratosVsLicencias into [$(vRutaQVDExtraccion)CMDB_ContratosVsLicencias.qvd](qvd);
//Drop Table CMDB_ContratosVsLicencias;




///$tab 2.2. FOTOSW_SCCM
FOTOSW_SCCM:
LOAD
    Nombre_Maquina,
    Serial,
    Dominio,
    Ultimo_Logon,
    Software,
    InstallDate01,
    Version01,
    Ultima_Revision
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/FOTOSW_SCCM.xlsx]
//(ooxml, embedded labels, table is Hoja1);

FROM [$(vRutaQVDExtraccionXlsx)FOTOSW_SCCM.xlsx]
(ooxml, embedded labels, table is [Hoja1]);

Store FOTOSW_SCCM into [$(vRutaQVDExtraccion)FOTOSW_SCCM.qvd](qvd);
Drop Table FOTOSW_SCCM;

///$tab 2.3. SW_listablanca
SW_listablanca:
LOAD
    SW,
    Análisis,
    "Fecha Análisis"
//    Observación,
//    Columna1
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/SW_gratuito_listablanca_listanegra.xlsx]
//(ooxml, embedded labels, table is [SW Lista Blanca]);


FROM [$(vRutaQVDExtraccionXlsx)SW_gratuito_listablanca_listanegra.xlsx]
(ooxml, embedded labels, table is [SW Lista Blanca]);

Store SW_listablanca into [$(vRutaQVDExtraccion)SW_listablanca.qvd](qvd);
Drop Table SW_listablanca;
///$tab 2.4. SW_listanegra
SW_listanegra:
LOAD
    SW,
    Observación
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/SW_gratuito_listablanca_listanegra.xlsx]
//(ooxml, embedded labels, table is [SW Lista Negra]);

FROM [$(vRutaQVDExtraccionXlsx)SW_gratuito_listablanca_listanegra.xlsx]
(ooxml, embedded labels, table is [SW Lista Negra]);

Store SW_listanegra into [$(vRutaQVDExtraccion)SW_listanegra.qvd](qvd);
Drop Table SW_listanegra;
///$tab 2.5. SW_vulnerabilidades
// SW_vulnerabilidades:
// LOAD
//     SW,
//     Análisis,
//     "Fecha Análisis",
//     Observación
// //FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/SW_gratuito_listablanca_listanegra.xlsx]
// //(ooxml, embedded labels, table is [SW con Vulnerabilidad]);

// FROM [$(vRutaQVDExtraccionXlsx)SW_gratuito_listablanca_listanegra.xlsx]
// (ooxml, embedded labels, table is [SW con Vulnerabilidad]);

// Store SW_vulnerabilidades into [$(vRutaQVDExtraccion)SW_vulnerabilidades.qvd](qvd);
// Drop Table SW_vulnerabilidades;
///$tab 3.1. AdministradorLocal
AdministradorLocal:
LOAD
    "Computer Name",
    "Name of the local Group",
    "Account Contained within the Group",
    "Account Type",
    "Domain for Account",
    "Type of Account",
    "User Loged On"
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/AdministradorLocal.xlsx]
//(ooxml, embedded labels, table is [Cuentas Grupo adrministrado]);

FROM [$(vRutaQVDExtraccionXlsx)AdministradorLocal.xlsx]
(ooxml, embedded labels, table is [Cuentas Grupo administradores]);

Store AdministradorLocal into [$(vRutaQVDExtraccion)AdministradorLocal.qvd](qvd);
Drop Table AdministradorLocal;
///$tab 3.2. PermisosAdministradorLocal
PermisosAdministradorLocal:

LOAD
    EQUIPOS,
    "# NUMERO DE ORDEN DE TRABAJO",
    "CATEGORIA GRUPO DE TRABAJO",
    "DOCUMENTACION/JUSTIFACION",
    LOGIN,
    EQUIPOS1,
    VIGENCIA,
    "WO RETIRO DE PERMISOS"
FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/PermisosAdministradorLocal.xlsx]
(ooxml, embedded labels, table is [Gestion permisos administrador]);

Store PermisosAdministradorLocal into [$(vRutaQVDExtraccion)PermisosAdministradorLocal.qvd](qvd);
Drop Table PermisosAdministradorLocal;




// LOAD
//     "# NUMERO DE ORDEN DE TRABAJO",
//     "CATEGORIA GRUPO DE TRABAJO",
//     "DOCUMENTACION/JUSTIFACION",
//     LOGIN,
//     EQUIPOS,
//     VIGENCIA,
//     "WO RETIRO DE PERMISOS"
// //FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/PermisosAdministradorLocal.xlsx]
// //(ooxml, embedded labels, table is Hoja1);

// FROM [$(vRutaQVDExtraccionXlsx)PermisosAdministradorLocal.xlsx]
// (ooxml, embedded labels, table is [Hoja1]);

// Store PermisosAdministradorLocal into [$(vRutaQVDExtraccion)PermisosAdministradorLocal.qvd](qvd);
// Drop Table PermisosAdministradorLocal;
///$tab 3.3. DA_Con_PermisosAdmonLocal
DA_Con_PermisosAdmonLocal:
LOAD
    "Nombre de directorio",
    WO,
    Vigencia,
    "WO RETIRO"
FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/PermisosAdministradorLocal.xlsx]
(ooxml, embedded labels, table is OuDesarrolloUpdate);

Store DA_Con_PermisosAdmonLocal into [$(vRutaQVDExtraccion)DA_Con_PermisosAdmonLocal.qvd](qvd);
Drop Table DA_Con_PermisosAdmonLocal;
///$tab 3.4. AntivirusPC
AntivirusPC:
LOAD
    Domain,
    Endpoint,
    "IP Address",
    "Listening Port",
    "Domain Hierarchy",
    "Connection Status",
    GUID,
    "Scan Method",
    "Data Protection Status",
    "File Reputation Services Status",
    "File Reputation Services URL",
    "Web Reputation Services Status",
    "Web Reputation Services URL",
    "Virus/Malware",
    "Spyware/Grayware",
    "Outbreak Prevention",
    //Firewall,
    //IDS,
    "Update Agent Components",
    "Update Agent Settings",
    "Update Agent Program and Hotfixes",
    Platform,
    Architecture,
    "MAC Address",
    "Agent Program",
    "Smart Scan Agent Pattern",
    "Virus Pattern",
    "Virus Regional CPR Pattern",
    "Virus Customized CPR Pattern",
    "IntelliTrap Pattern",
    "IntelliTrap Exception Pattern",
    "Virus Scan Engine",
    "Spyware/Grayware Pattern v.6",
    "Spyware/Grayware Pattern",
    "Spyware/Grayware Scan Engine",
    "Damage Cleanup Template",
    "Damage Cleanup Engine",
    //"Common Firewall Pattern",
    //"Common Firewall Driver",
    "Behavior Monitoring Driver",
    "Behavior Monitoring Core Service",
    "Behavior Monitoring Configuration Pattern",
    "Digital Signature Pattern",
    "Policy Enforcement Pattern",
    "Behavior Monitoring Detection Pattern",
    "Last Startup",
    "Last Shutdown",
    "Agent Installation",
    "Agent Upgrade",
    Hotfix,
    "Restart Required",
//     "Firewall Policy",
//     "Firewall Logs",
//     "IDS Logs",
//     "Network Virus Logs",
//     "Firewall Logs/Hour",
//     "IDS Logs/Hour",
//     "Network Virus Logs/Hour",
//     "Last Firewall Count Sent",
//     "Last Virus Scan (Manual)",
    "Last Virus Detection (Real-time)",
    "Last Virus Scan (Scheduled)",
    "Last Virus Scan (Scan Now)",
    "Last Spyware Scan (Manual)",
    "Last Spyware Detection (Real-time)",
    "Last Spyware Scan (Scheduled)",
    "Last Spyware Scan (Scan Now)",
    "Early Boot Cleanup Driver",
    "Global C&C IP List",
    "Relevance Rule Pattern",
    "Memory Inspection Pattern",
    "Memory Scan Trigger Pattern",
    "Browser Exploit Prevention Pattern",
    "Script Analyzer Unified Pattern",
    "Logon User",
    "Program Inspection Monitoring Pattern",
    "Damage Recovery Pattern",
    "Data Protection Module",
    "Early Launch Anti-Malware Pattern",
    "Contextual Intelligence Engine",
    "Contextual Intelligence Pattern",
    "Contextual Intelligence Query Handler",
    "Advanced Threat Scan Engine",
    "Advanced Threat Correlation Pattern"
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/AntivitusPC.xlsx]
//(ooxml, embedded labels, table is [Exporte general 6 de Marzo]);

FROM [$(vRutaQVDExtraccionXlsx)AntivirusPC.xlsx]
(ooxml, embedded labels, table is [AntivirusPC]);

Store AntivirusPC into [$(vRutaQVDExtraccion)AntivirusPC.qvd](qvd);
Drop Table AntivirusPC;
///$tab 3.5. AntivirusServidores
AntivirusServidores:

LOAD
    Name,
    Platform,
    Policy,
    Status,
    "Last IP Used"
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/AntivirusServidores.xlsx]
//(ooxml, embedded labels, table is [Exporte Servers]);


FROM [$(vRutaQVDExtraccionXlsx)AntivirusServidores.xlsx]
(ooxml, embedded labels, table is [AntivirusServidores]);

Store AntivirusServidores into [$(vRutaQVDExtraccion)AntivirusServidores.qvd](qvd);
Drop Table AntivirusServidores;
///$tab 4. SWDardeBaja
SWDardeBaja:
LOAD
    "Work Order ID",
    "Categorization Tier 2",
    Summary,
    "Status WO",
    "Submit Date",
    "Completed Date",
    Notes,
    "Request Assignee",
    ASGRP,
    WOI_CI,
    Service,
    "Categorization Tier 1",
    "Categorization Tier 3",
    "Product Cat Tier 1(2)",
    "Product Cat Tier 2 (2)",
    "Product Cat Tier 3 (2)",
    "Product Name (2)",
    "Service Cat Tier 1",
    "Service Cat Tier 2",
    "Service Cat Tier 3",
    Sequence,
    "Task ID",
    TaskName,
    Status,
    StatusReasonSelection,
    ContactFullName,
    Company,
    "Assigned To",
    Assignee,
    "Assignee Group",
    Department,
    "Customer First Name",
    "Customer Last Name",
    "Total Minutos Activo Tarea",
    "Total Horas Activo Tarea",
    "Inicia Asignación Tarea",
    "Termina Asignación Tarea",
    "Total Horas Activo WO",
    "Business Service"
//FROM [lib://EPM_File_02 (epm_dcarmond)/Service_Desk/Remedy_epm/Auditoria/Evaluación vigente/SWDardeBaja.xlsx]
//(ooxml, embedded labels, table is [1-ProvisionSW Dar de Baja Softw]);

FROM [$(vRutaQVDExtraccionXlsx)SWDardeBaja.xlsx]
(ooxml, embedded labels, table is [SWDardeBaja]);

Store SWDardeBaja into [$(vRutaQVDExtraccion)SWDardeBaja.qvd](qvd);
Drop Table SWDardeBaja;
///$tab 5. Reporte_SNOW
Reporte_SNOW:
LOAD
    "Computer name",
    Organisation,
    Serial,
    "Last logged on user",
    "Application",
    "Application manufacturer",
    "Default metric",
    "License required",
    Installed,
    "Last scanned",
    Status


FROM [$(vRutaQVDExtraccionXlsx)Reporte_SNOW.xlsx]
(ooxml, embedded labels, table is [Applications per computer]);

Store Reporte_SNOW into [$(vRutaQVDExtraccion)Reporte_SNOW.qvd](qvd);
Drop Table Reporte_SNOW;
///$tab Exit Script
TRACE -->############### Salida ###############;

// TRACE --> Se eliminan las variables innecesarias del QVF;
// CALL Funciones.EliminarRutas;
// CALL Funciones.EliminarVariables('vInicioScript,vNombreTabla');

TRACE --> Fin del Script;
EXIT SCRIPT;